# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MGGridViewTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MGGridViewTest
  pod 'MGGridView', '~> 0.1.1'

  target 'MGGridViewTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MGGridViewTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
